import React, { Component } from 'react';
import { connect } from 'react-redux';
// to make sure that the action generated by the action creator
// actually ends up flowing though all the different reducers.

class BookDetail extends Component {
  render() {
    if(!this.props.book) {
      return <div> Select a book to get started.</div>;
    }

    return (
      <div>
        <h3>Details for: </h3>
        <div>Title :{this.props.book.title}</div>
        <div>Pages : {this.props.book.pages}</div>
      </div>
    );
  }
}

// activeBook is being created by our ActiveBook reducer.
function mapStateToProps(state){
  return {
      book: state.activeBook
  }
}

export default connect(mapStateToProps)(BookDetail);
